name: gemini
description: A command-line application for finding duplicate files.
version: 1.0.1
homepage: https://github.com/Ampless/gemini

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  gemini: gemini

dependencies:
  crypto: ^3.0.2

dev_dependencies:
  lints: ^2.0.0
