name: gemini
description: A command-line application for finding duplicate files.
version: 1.1.0
homepage: https://github.com/Ampless/gemini

environment:
  sdk: '>=2.17.0 <3.0.0'

executables:
  gemini: gemini

dependencies:
  proper_filesize: ^0.0.2
  to_hex_string: ^1.0.0
  xxh3: ^1.0.1

dev_dependencies:
  lints: ^2.0.0
